#!/usr/bin/env python

bld(
	features = 'cxx cxxshlib com',
	source = bld.path.ant_glob('*.cpp *.idl *.rc') + [ 'ComTest_i.c' ],
	target = 'ComTest',
	defs = 'ComTest.def',
	includes = '.',
)
