#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'Peach.Core.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Peach.Core.Proxy.Web.Tester.exe',
)

