#!/bin/sh

if [ "$1" == "" ]; then
	echo "Usage: $0 <host> [waf options]"
	exit 1
fi

HOST=$1
SELF=`hostname`
LOCAL="`pwd`"
PROJ="`basename "$LOCAL"`"
REMOTE="jobs/${SELF}/${PROJ// /\\ }"

shift

ssh $HOST "mkdir -p ${REMOTE}"
rsync -avz --delete --exclude=.git --exclude-from=.gitignore "${LOCAL}/" "${HOST}:${REMOTE}/"
ssh $HOST "export TERM=msys; cd ${REMOTE} && ./waf configure build install $*"
