#!/usr/bin/env python

VERSION = '1.7.9'

import sys, os, os.path

if sys.platform == "cygwin":
        print 'waf must be run from cmd.exe'
        sys.exit(1)

if os.getenv('DevEnvDir'):
        print 'waf can not be run from a Visual Studio Command Prompt'
        sys.exit(1)

cwd = os.getcwd()
build = os.path.join(cwd, 'build')
wafdir = os.path.join(cwd, '3rdParty', 'waf')
sys.path = [ build, wafdir ] + sys.path

if __name__ == '__main__':
	from waflib import Scripting
	Scripting.waf_entry_point(cwd, VERSION, wafdir)
