#!/usr/bin/env python

deps = [
	'EasyHook.dll',
	'System.dll',
	'System.Core.dll',
	'Peach.Core.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachHooker.File.dll',
)
