#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Runtime.Remoting.dll',
	'EasyHook.dll',
	'PeachHooker.Network.dll',
	'PeachHooker.File.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachHooker.exe',
)



