#!/usr/bin/env python

def make_bld(tgt, variant):
	clone = bld.clone_env(variant)
	if clone is None:
		return
	bld(
		features = 'cxx cxxshlib pin release',
		source = 'bblocks.cpp',
		target=tgt,
		env=clone,
	)

if bld.env.DEST_OS is 'win32':
	make_bld('bblocks32', 'win_x86_release')
	if bld.env.SUBARCH is 'x64':
		make_bld('bblocks64', 'win_x64_release')

elif bld.env.DEST_OS is 'linux':
	make_bld('bblocks32', 'linux_x86_release')
	if bld.env.SUBARCH is 'x86_64':
		make_bld('bblocks64', 'linux_x86_64_release')

else:
	make_bld('bblocks', bld.variant)
