#!/usr/bin/env python

deps = [
	'NLog.dll',
	'Peach.Core.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',	
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.ServiceProcess.dll',
]

asm = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Core.OS.Windows.dll',
)

if 'win' in bld.env['supported_features']:
	asm.install_755 = bld.path.ant_glob('Debuggers/DebugEngine/*.dll')
