#!/usr/bin/env python

deps = [
	'NLog.dll',
	'Peach.Core.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.ServiceProcess.dll',
]

bld(
	features = 'cs win',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Core.OS.Windows.dll',
	install = bld.path.ant_glob('Debuggers/DebugEngine/*.dll'),
)
