#!/usr/bin/env python

deps = [
	'nunit.framework.dll',
	'NLog.dll',
	'System.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Windows.Forms.dll',
	'Microsoft.CSharp.dll',
	'Peach.Core.dll',
	'Peach.Core.OS.Windows.dll',
	'Peach.Core.Test.dll',
]

# Even though this should build via mono, this assembly causes mcs to segfault
# so noly build on windows fore the time being...

bld(
	features = 'cs win test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Core.Test.OS.Windows.dll',
)
