#!/usr/bin/env python

bld(
	features = 'cs',
	use = 'NLog.dll SharpPcap.dll Peach.Core.dll System.dll System.Xml.dll',
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.exe',
	ver_product = 'Peach Fuzzing Platfom',
	install = bld.path.ant_glob('samples/* *.xml')
)

