#!/usr/bin/env python
from waflib import Utils

name = 'Peach.exe'

app = bld(
	features = 'cs',
	use = 'NLog.dll SharpPcap.dll PacketDotNet.dll Peach.Core.dll System.dll System.Xml.dll',
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.exe',
	ver_product = 'Peach Fuzzing Platfom',
	install_644 = bld.path.ant_glob('peach.xsd template.xml samples/*')
)

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	app.install_755 = 'peach'
