#!/usr/bin/env python
from waflib import Utils

name = 'Peach.exe'

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	name = 'peach.exe'
	bld.install_files('${BINDIR}', 'peach', chmod=Utils.O755)

bld(
	features = 'cs',
	use = 'NLog.dll SharpPcap.dll Peach.Core.dll System.dll System.Xml.dll',
	source = bld.path.ant_glob('**/*.cs'),
	name = name,
	namespace = 'Peach',
	ver_product = 'Peach Fuzzing Platfom',
	install = bld.path.ant_glob('template.xml samples/*')
)
