#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'Peach.Core.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',	
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachMinset.exe',
)



