#!/usr/bin/env python

deps = [
	'NLog.dll',
	'CookComputing.XmlRpcV2.dll',
	'SharpPcap.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Data.dll',
	'System.Web.dll',
	'Ionic.Zip.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'IronRuby.dll',
	'IronRuby.Libraries.dll',
	'IronRuby.Libraries.Yaml.dll',
	'Microsoft.Dynamic.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
]

foo = bld(
	features = 'cxx cxxshlib',
	use = deps,
#	source = bld.path.ant_glob('**/*.cpp'),
	name = 'Peach.Core.Debuggers.Windows',
)

foo.env.append_value('CXXFLAGS', ['/clr', '/Zc:wchar_t'])
foo.env.append_value('DEFINES', ['WIN32', 'UNICODE' ])
