#!/usr/bin/env python

app = bld(
	features = 'cxx cxxprogram debug',
	source = 'CrashingProgram.cpp',
	target='CrashingProgram',
)

if 'msvc' == app.env.CC_NAME:
	# Disable buffer security checks so we get 2nd chance AV exceptions
	app.env.append_value('CXXFLAGS', [ '/GS-' ])
