#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'Mono.Posix.dll',
]


bld(
	features = 'cs linux',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachLinuxCrashHandler.exe',
)



