#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Windows.Forms.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'Peach.Core.dll',
	
]

bld(
	features = 'cs',
	use = deps,
	bintype = 'winexe',
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachNetworkFuzzer.exe',
)



