#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
	conf.load('gcc gas')

def build(bld):
	# http://docs.waf.googlecode.com/git/apidocs_16/tools/asm.html
	bld.program(
		source = 'main.c test.S',
		target = 'asmtest')

