#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',	
	'System.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.Windows.Forms.dll',
	'System.Xml.dll',
]

bld(
	features = 'cs',
	use = deps,
	bintype = 'winexe',
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name='PeachXmlGenerator.exe',
)
