#!/usr/bin/env python

deps = [
	'Peach.Core.Xml.dll',
	'System.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.Windows.Forms.dll',
	'System.Xml.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name='PeachXmlGenerator.exe',
	config='app.config',
)
