#!/usr/bin/env python

deps = [
	'NLog.dll',
	'SharpPcap.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Web.dll',
	'Ionic.Zip.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'IronRuby.dll',
	'IronRuby.Libraries.dll',
	'IronRuby.Libraries.Yaml.dll',
	'Microsoft.Dynamic.dll',
	'Microsoft.CSharp.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	'Peach.Core.dll',
	'Mono.Posix.dll',
]

bld(
	features = 'cs linux',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Peach.Core.OS.Linux.dll',
	install = bld.path.ant_glob('gdb/**/*'),
)
