#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Web.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'IronRuby.dll',
	'IronRuby.Libraries.dll',
	'IronRuby.Libraries.Yaml.dll',
	'Microsoft.Dynamic.dll',
	'Microsoft.CSharp.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	'Peach.Core.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',	
	'Mono.Posix.dll',
]

asm = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Peach.Core.OS.Linux.dll',
)

if 'linux' in bld.env['supported_features']:
	asm.install_755 = bld.path.ant_glob('gdb/**/*')
