#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'System.Web.dll',
	'System.Web.Services.dll',
	'Peach.Core.dll',
	'Peach.Core.OS.Windows.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='TestThings.exe',
)



